import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { AGT002_RADAR_PIPELINE_STAGES,createAgt002RadarPipeline } from '../agt002-radar-pipeline.js';
const NOW='2026-08-25T15:00:00.000Z',TENDER={id:'22222222-2222-4222-8222-222222222222',stable_key:'k-1',title:'Vigilancia',description:'Armada',source:'SECOP II',entity:'E',city:'Bogotá',dept:'Cundinamarca',category:'Licitación'};
const hostileDatabase=new Proxy({},{get(){throw new Error('database must not be touched');}}),hostile=()=>{throw new Error('must not run');};
for(const environment of [{},{AGT002_RADAR_GATE:'false'},{AGT002_RADAR_GATE:'yes'},{AGT002_RADAR_GATE:''}]){const disabled=createAgt002RadarPipeline({database:hostileDatabase,environment,now:()=>NOW,fetchTenderPage:hostile,evaluateGate:hostile,recordGateEvaluation:hostile,enqueueJob:hostile,claimJob:hostile,completeJob:hostile,failJob:hostile,projectLearningObservations:hostile,buildLearningSignals:hostile,runPreanalysis:hostile,recordPreanalysisRun:hostile});assert.deepEqual(await disabled.runOnce(),{status:'disabled',stages:[],code:'AGT002_RADAR_PIPELINE_DISABLED'});}
const calls=[];let nowCalls=0;const gateClockValues=[];const track=(name,value)=>(...args)=>{calls.push(name);return typeof value==='function'?value(...args):value;};
const enabled=createAgt002RadarPipeline({database:{},environment:{AGT002_RADAR_GATE:'true'},now:()=>{nowCalls+=1;return NOW;},
 fetchTenderPage:track('fetch',[TENDER,{id:'33333333-3333-4333-8333-333333333333',stable_key:'k-2'}]),
 evaluateGate:track('gate',(row,{nowIso})=>{gateClockValues.push(nowIso);return row.stable_key==='k-1'?{verdict:'sobreviviente',rule_ids:[],reasons:[],data_gaps:[],tender_id:row.id,source_row_hash:'a'.repeat(64),policy_version:'p',context_version:'c'}:{verdict:'eliminada',rule_ids:['estado_terminal'],reasons:[{rule_id:'estado_terminal'}],data_gaps:[],tender_id:row.id,source_row_hash:'b'.repeat(64),policy_version:'p',context_version:'c'};}),
 recordGateEvaluation:track('ledger',value=>({id:value.tenderId===TENDER.id?'gate-1':'gate-2'})),enqueueJob:track('enqueue',{status:'created',job_id:'j1'}),claimJob:track('claim',{jobId:'j1',leaseId:'l1',tenderId:TENDER.id,gateEvaluationId:'gate-1',attemptKey:'a1'}),projectLearningObservations:track('learning',{precedents:[]}),buildLearningSignals:track('signals',({candidate,maxSignals})=>{assert.equal(candidate.tender_id,TENDER.id);assert.equal(maxSignals,10);return{version:'agt002-radar-learning-v1',candidate_id:TENDER.id,max_signals:10,considered:0,signals:[]};}),runPreanalysis:track('agt',{status:'completed',visibility_verdict:'mostrar_en_radar',evidence:[{evidence_id:'e'}],usage:{},policy_version:'p',context_version:'c'}),recordPreanalysisRun:track('persist',{id:'r1',canonical:true}),completeJob:track('complete',{status:'completed'}),failJob:hostile});
const result=await enabled.runOnce();assert.equal(result.status,'completed');assert.equal(result.job_id,'j1');assert.equal(result.preanalysis_run_id,'r1');assert.equal(result.evaluated,2);assert.equal(result.survivors,1);assert.equal(result.eliminated,1);assert.deepEqual([...new Set(calls)],['fetch','gate','ledger','enqueue','claim','learning','signals','agt','persist','complete']);assert.deepEqual(result.stages,AGT002_RADAR_PIPELINE_STAGES);assert.equal(calls.filter(x=>x==='ledger').length,2);assert.equal(calls.filter(x=>x==='enqueue').length,1);assert.equal(calls.filter(x=>x==='claim').length,1);assert.equal(calls.filter(x=>x==='agt').length,1);assert.equal(nowCalls,1);assert.deepEqual(gateClockValues,[NOW,NOW]);
const empty=createAgt002RadarPipeline({database:{},environment:{AGT002_RADAR_GATE:'1'},now:()=>NOW,fetchTenderPage:async()=>[],evaluateGate:hostile,recordGateEvaluation:hostile,enqueueJob:hostile,claimJob:async()=>null,completeJob:hostile,failJob:hostile,projectLearningObservations:hostile,buildLearningSignals:hostile,runPreanalysis:hostile,recordPreanalysisRun:hostile});assert.equal((await empty.runOnce()).status,'empty');
let failedCode;const learningBroken=createAgt002RadarPipeline({database:{},environment:{AGT002_RADAR_GATE:'true'},now:()=>NOW,fetchTenderPage:async()=>[TENDER],evaluateGate:()=>({verdict:'sobreviviente',rule_ids:[],reasons:[],data_gaps:[],tender_id:TENDER.id,source_row_hash:'a'.repeat(64),policy_version:'p',context_version:'c'}),recordGateEvaluation:async()=>({id:'gate-1'}),enqueueJob:async()=>({status:'created',job_id:'j1'}),claimJob:async()=>({jobId:'j1',leaseId:'l1',tenderId:TENDER.id,gateEvaluationId:'gate-1',attemptKey:'a1'}),projectLearningObservations:async()=>{const error=new Error('down');error.runtime_boundary_code='AGT002_RADAR_LEARNING_SIGNALS_INVALID';throw error;},buildLearningSignals:hostile,runPreanalysis:hostile,recordPreanalysisRun:hostile,completeJob:hostile,failJob:async(_db,{errorCode})=>{failedCode=errorCode;}});assert.deepEqual(await learningBroken.runOnce(),{status:'unavailable',stages:['fetch','gate','ledger','claim','learning'],job_id:'j1',error_code:'invalid_output'});assert.equal(failedCode,'invalid_output');
let enqueueCalled=false;const ledgerBroken=createAgt002RadarPipeline({database:{},environment:{AGT002_RADAR_GATE:'true'},now:()=>NOW,fetchTenderPage:async()=>[TENDER],evaluateGate:()=>({verdict:'sobreviviente',tender_id:TENDER.id,source_row_hash:'a'.repeat(64),policy_version:'p',context_version:'c'}),recordGateEvaluation:async()=>{throw new Error('down');},enqueueJob:()=>{enqueueCalled=true;},claimJob:hostile,projectLearningObservations:hostile,buildLearningSignals:hostile,runPreanalysis:hostile,recordPreanalysisRun:hostile,completeJob:hostile,failJob:hostile});assert.equal((await ledgerBroken.runOnce()).status,'unavailable');assert.equal(enqueueCalled,false);
const source=readFileSync(new URL('../agt002-radar-pipeline.js',import.meta.url),'utf8');assert.doesNotMatch(source,/Date\.now\(\)|new Date\(\)/);assert.doesNotMatch(source,/learning-proposals/);
console.log('AGT-002 real ordered pipeline and default-off no-op passed');
