import { readFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';
import { buildSync } from 'esbuild';
const types = readFileSync(new URL('../src/tenders/types.ts', import.meta.url), 'utf8');
const view = readFileSync(new URL('../src/tenders/TenderRadarView.tsx', import.meta.url), 'utf8');
const bundled = buildSync({ entryPoints: [new URL('../src/tenders/radarUtils.ts', import.meta.url).pathname], bundle: true, platform: 'node', format: 'esm', write: false });
const { filterRadarTenders, sortTenderCards } = await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].contents).toString('base64')}`);
assert.match(types, /TenderScoreFilter = 'todas' \| 'alto' \| 'medio' \| 'por_validar' \| 'bajo'/);
assert.match(types, /fit\?: TenderFitProjection/);
const reasonType = types.match(/export type TenderFitReason = \{[^}]*\};/);
assert.ok(reasonType, 'TenderFitReason debe estar declarado');
assert.match(reasonType[0], /axis: string/);
assert.match(reasonType[0], /points: number/);
assert.match(reasonType[0], /code: string/, 'TenderFitReason debe exponer code (código estable del motivo)');
assert.match(reasonType[0], /detail: string/);
assert.match(reasonType[0], /source: string/, 'TenderFitReason debe exponer source (campo de origen del motivo)');
const dataGapType = types.match(/export type TenderFitDataGap = \{[^}]*\};/);
assert.ok(dataGapType, 'TenderFitDataGap debe estar declarado');
assert.match(dataGapType[0], /gap_id: string/);
assert.match(dataGapType[0], /field: string/);
assert.match(dataGapType[0], /severity: 'critical' \| 'noncritical'/);
assert.match(dataGapType[0], /detail: string/, 'TenderFitDataGap debe exponer detail (explicación legible de la brecha)');
assert.match(dataGapType[0], /source: string/, 'TenderFitDataGap debe exponer source (campo de origen de la brecha)');
const baseFilters = { query: '', source: 'todas', region: 'todas', deadline: 'todas', value: 'todas', score: 'todas', section: 'todas', internalStatus: 'todas' };
const conFit = { id: 'a', source: 'S', entity: 'E', title: 'T', section: 'hacer', score: 10, value: 1, fit: { band: 'por_validar', score: 40 } };
const sinFit = { id: 'b', source: 'S', entity: 'E', title: 'T', section: 'hacer', score: 80, value: 1 };
assert.deepEqual(filterRadarTenders([conFit], { ...baseFilters, score: 'por_validar' }).map(t => t.id), ['a']);
assert.deepEqual(filterRadarTenders([conFit], { ...baseFilters, score: 'alto' }), [], 'con fit no debe leer el score legado');
assert.deepEqual(filterRadarTenders([sinFit], { ...baseFilters, score: 'alto' }).map(t => t.id), ['b'], 'sin fit cae al umbral legado score>=70');
assert.deepEqual(filterRadarTenders([sinFit], { ...baseFilters, score: 'por_validar' }), [], 'sin fit, por_validar nunca coincide');
const alto = { ...conFit, id: 'alto', fit: { band: 'alto', score: 90 } };
const bajo = { ...conFit, id: 'bajo', fit: { band: 'bajo', score: 10 } };
assert.deepEqual(sortTenderCards([bajo, alto], 'score', 'desc').map(t => t.id), ['alto', 'bajo']);
assert.deepEqual(sortTenderCards([{ ...sinFit, id: 'la', score: 90 }, { ...sinFit, id: 'lb', score: 10 }], 'score', 'desc').map(t => t.id), ['la', 'lb'], 'fallback legado sin fit');
assert.match(view, /<option value="medio">Medio<\/option><option value="por_validar">Por validar<\/option><option value="bajo">Bajo<\/option>/);
console.log('tender-fit-frontend: OK');
