import { readFileSync } from 'node:fs';

const src = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const server = readFileSync(new URL('../server/index.js', import.meta.url), 'utf8');
const api = readFileSync(new URL('../api/[...path].js', import.meta.url), 'utf8');

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

assert(src.includes("'tenders'"), 'Frontend debe incluir ruta tenders/licitaciones.');
assert(src.includes("#/tenders','Licitaciones'"), 'Sidebar debe incluir pestaña Licitaciones.');
assert(src.includes('canViewTenders'), 'Frontend debe ocultar Licitaciones según rol/persona autorizada.');
assert(src.includes('directora.licitaciones@seguridadnacional.co'), 'Katherine debe estar autorizada explícitamente para ver Licitaciones.');
assert(src.includes('TendersRadar'), 'Frontend debe incluir componente TendersRadar.');
assert(src.includes("api<TenderRadarPayload>('/api/tenders')"), 'Licitaciones debe cargar datos desde /api/tenders.');
assert(src.includes('Crear oportunidad'), 'Licitaciones debe permitir convertir una licitación en oportunidad.');
assert(src.includes('createOpportunityFromTender'), 'Frontend debe tener acción createOpportunityFromTender para convertir licitación.');
assert(src.includes("service_type_code: 'licitacion_publica'"), 'La oportunidad creada desde licitación debe quedar como servicio Licitación Pública.');
assert(src.includes("stage_code: 'prospecto'"), 'La oportunidad creada desde licitación debe entrar como Prospecto.');
assert(src.includes('findTenderOwner'), 'Frontend debe asignar la oportunidad a Katherine o al usuario de licitaciones.');
assert(src.includes("api<{id:string}>('/api/tender-convert'"), 'La conversión debe usar alias Vercel-safe /api/tender-convert para bloquear duplicados y marcar convertido.');
assert(src.includes("api<TenderRadarPayload>('/api/tender-refresh'"), 'La sincronización debe usar alias Vercel-safe /api/tender-refresh.');
assert(src.includes('api<PublicTender>(`/api/tender-status'), 'Los estados internos deben usar alias Vercel-safe /api/tender-status.');
assert(!src.includes('disabled title="Fase 2"'), 'El botón Crear oportunidad en Licitaciones ya no debe estar deshabilitado como fase futura.');
assert(src.includes('TenderInternalStatus'), 'Frontend debe modelar estado interno de licitación.');
assert(src.includes('markTenderStatus'), 'Frontend debe permitir marcar En revisión / Descartada.');
assert(src.includes('converted_opportunity_id'), 'Frontend debe mostrar licitaciones ya convertidas con enlace a oportunidad.');
assert(!src.includes('Radar público SECOP'), 'Frontend no debe amarrar el módulo solo a SECOP.');
assert(src.includes('Radar de Licitaciones Públicas'), 'Frontend debe presentar el radar como multifuente.');
assert(src.includes('Sincronizar fuentes'), 'Frontend debe tener acción explícita de sincronización multifuente.');
assert(!src.includes('Sincronizar SECOP'), 'El botón ya no debe decir Sincronizar SECOP.');
assert(src.includes('Abrir fuente'), 'Frontend debe abrir la fuente genérica, no solo SECOP.');
assert(src.includes('diagnostics'), 'Frontend debe mostrar diagnóstico de fuentes, incluyendo TVEC temporalmente no disponible.');
assert(src.includes('Estado interno'), 'Frontend debe mostrar/filtar estado interno.');
assert(src.includes('TenderQuickFilter'), 'Licitaciones debe tener tipo de filtro rápido para KPIs accionables.');
assert(src.includes('applyTenderQuickFilter'), 'KPIs de Licitaciones deben filtrar la bandeja al hacer click.');
assert(src.includes('tender-kpi-filter'), 'KPIs de Licitaciones deben tener estilo/estado clicable.');
assert(src.includes('Ver procesos prioritarios'), 'KPI Hacer hoy debe comunicar que abre el filtro correspondiente.');
assert(src.includes('Ver procesos $500M+'), 'KPI Alto valor debe abrir filtro por valor alto.');
assert(src.includes('Recargar vista'), 'Botón ambiguo Actualizar debe renombrarse a Recargar vista.');
assert(src.includes('Sincronizar fuentes oficiales'), 'Botón de sincronización debe explicar que consulta fuentes oficiales.');
assert(src.includes('Recargar vista actualiza los datos guardados'), 'La UI debe explicar diferencia entre recargar y sincronizar.');
assert(src.includes('Limpiar filtros'), 'Licitaciones debe permitir limpiar filtros.');
assert(src.includes('sourceFilter'), 'Licitaciones debe filtrar por fuente.');
assert(src.includes('deadlineFilter'), 'Licitaciones debe filtrar por cierre.');
assert(src.includes('valueFilter'), 'Licitaciones debe filtrar por valor.');
assert(src.includes('scoreFilter'), 'Licitaciones debe filtrar por encaje/score.');
assert(src.includes('activeTenderFilterChips'), 'Licitaciones debe mostrar chips de filtros activos.');
assert(src.includes('“Hacer hoy” prioriza procesos'), 'Licitaciones debe explicar cómo se clasifica la bandeja.');
assert(src.includes('tender-source-badge'), 'Cada licitación debe resaltar la fuente.');
assert(src.includes('tender-deadline-pill'), 'Cada licitación debe mostrar el cierre como pill operativo.');
assert(src.includes('fmtTenderDeadline'), 'Frontend debe formatear cierre con vencida/vence en/sin fecha.');
assert(src.includes('fmtMoneyCompact(tender.value)'), 'Cada licitación debe mostrar valor compacto.');
assert(src.includes('tender-card-actions'), 'Acciones de cada licitación deben quedar agrupadas visualmente.');
assert(src.includes('Refinar resultados'), 'La barra debe distinguir filtros principales y refinamiento operativo adicional.');
assert(src.includes('tender-control-panel'), 'Licitaciones debe agrupar búsqueda, acciones y filtros en un panel de control claro.');
assert(src.includes('tender-results-toolbar'), 'Licitaciones debe separar resumen/ordenamiento del panel de filtros.');
assert(src.includes('tender-help-panel'), 'La explicación larga y diagnóstico deben quedar en un panel colapsable.');
assert(src.includes('TenderFastFilter'), 'Licitaciones debe tener filtros rápidos operativos separados de KPIs.');
assert(src.includes('applyTenderFastFilter'), 'Los filtros rápidos deben mapear a los tipos existentes sin crear taxonomía paralela.');
assert(src.includes('tender-fast-filters'), 'La UI debe renderizar una fila visual de filtros rápidos.');
assert(src.includes('Nuevas'), 'Filtros rápidos debe incluir Nuevas.');
assert(src.includes('Urgentes'), 'Filtros rápidos debe incluir Urgentes.');
assert(src.includes('Alto encaje'), 'Filtros rápidos debe incluir Alto encaje.');
assert(src.includes("deadlineFilter: '0_7'"), 'Urgentes debe mapear al tipo existente 0_7.');
assert(src.includes("valueFilter: '500m_plus'"), 'Alto valor debe mapear al tipo existente 500m_plus.');
assert(src.includes("scoreFilter: 'alto'"), 'Alto encaje debe mapear al tipo existente alto.');
assert(src.includes('isTenderPrioritizable'), 'Las descartadas/convertidas no deben aparecer como prioritarias.');
assert(src.includes("status !== 'descartada'"), 'La priorización visual debe excluir licitaciones descartadas.');
assert(src.includes('tender-deadline-overdue'), 'Las licitaciones vencidas deben tener clase visual específica.');
assert(src.includes('tender-deadline-urgent'), 'Las licitaciones urgentes deben tener clase visual específica.');
assert(src.includes('tender-deadline-soon'), 'Las licitaciones próximas deben tener clase visual específica.');
assert(src.includes('tender-deadline-empty'), 'Las licitaciones sin fecha deben tener clase visual específica.');
assert(!src.includes('Régimen especial web'), 'No se deben agregar fuentes web fijas si no existen en los datos.');
assert(!src.includes('Privado web'), 'No se deben agregar fuentes privadas fijas si no existen en los datos.');
assert(src.includes('TENDER_OFFICIAL_SOURCES'), 'El filtro de fuente debe incluir fuentes oficiales confirmadas aunque una fuente no devuelva resultados en la última corrida.');
assert(src.includes('ESU Contratación'), 'El filtro de fuente debe mostrar ESU Contratación como fuente oficial confirmada.');
assert(src.includes('<span>Prioridad</span>'), 'El filtro principal debe llamarse solo Prioridad.');
assert(src.includes('["todas","Todas"]'), 'El predeterminado de cada dropdown de licitaciones debe ser Todas.');
assert(src.includes('empty=""'), 'Los dropdowns de licitaciones no deben inyectar una opción/header interna adicional.');
assert(!src.includes('placeholderOption'), 'No debe quedar helper legacy que genere opciones tipo "Filtro: Todas".');
assert(src.includes('["urgentes","Urgentes"]'), 'El filtro principal debe mostrar Urgentes sin repetir el nombre del filtro.');
assert(src.includes('["alto_valor","Alto valor"]'), 'El filtro principal debe mostrar Alto valor sin repetir el nombre del filtro.');
assert(src.includes('["alto_encaje","Alto encaje"]'), 'El filtro principal debe mostrar Alto encaje sin repetir el nombre del filtro.');
assert(src.includes('tender-filter-field'), 'Cada dropdown de licitaciones debe tener etiqueta externa para evitar opciones redundantes.');
assert(!src.includes('Prioridad / filtro: Todas'), 'Las opciones del dropdown no deben repetir Prioridad / filtro en Todas.');
assert(!src.includes('["todas","Prioridad"]'), 'Prioridad no debe aparecer como opción interna del dropdown.');
assert(!src.includes('Estado interno: Todas'), 'Las opciones del dropdown no deben repetir Estado interno en Todas.');
assert(!src.includes('Cierre: Todas'), 'Las opciones del dropdown no deben repetir Cierre en Todas.');
assert(src.includes('primaryTenderFilter'), 'La UI debe tener un filtro principal unificado para prioridad/operación.');
assert(src.includes('TenderUnifiedBoard'), 'Licitaciones debe usar una sola vista unificada de tarjetas operativas.');
assert(src.includes('Vista unificada de licitaciones'), 'La UI debe comunicar que la bandeja fue unificada.');
assert(!src.includes('<TenderTable rows='), 'No debe alternar entre tabla y tarjetas según el filtro; usar una sola forma de mostrar datos.');
assert(src.includes('TenderSortKey'), 'Las tarjetas de licitaciones deben tener tipo de ordenamiento propio.');
assert(src.includes('tenderSortKey'), 'La vista unificada debe guardar el campo por el que ordena tarjetas.');
assert(src.includes('tenderSortDirection'), 'La vista unificada debe permitir alternar dirección ascendente/descendente.');
assert(src.includes('sortTenderCards'), 'Debe existir función dedicada para ordenar tarjetas filtradas.');
assert(src.includes('Ordenar por'), 'La UI debe mostrar controles de ordenamiento para las tarjetas.');
assert(src.includes('Mayor valor primero'), 'Debe permitir ordenar por valor descendente.');
assert(src.includes('Cierre más próximo'), 'Debe permitir ordenar por cierre próximo.');
assert(src.includes('Entidad A-Z'), 'Debe permitir ordenar alfabéticamente por entidad.');
assert(src.includes('Score alto primero'), 'Debe permitir ordenar por score descendente.');

for (const file of [server, api]) {
  assert(file.includes('canViewTenders'), 'API debe tener guard canViewTenders.');
  assert(file.includes("app.get('/api/tenders'"), 'API debe exponer GET /api/tenders.');
  assert(file.includes("app.post('/api/tenders/refresh'"), 'API debe exponer POST /api/tenders/refresh para persistir radar.');
  assert(file.includes("app.post('/api/tender-refresh'"), 'API debe exponer alias Vercel-safe POST /api/tender-refresh.');
  assert(file.includes("app.patch('/api/tenders/:id/status'"), 'API debe exponer PATCH /api/tenders/:id/status.');
  assert(file.includes("app.patch('/api/tender-status'"), 'API debe exponer alias Vercel-safe PATCH /api/tender-status.');
  assert(file.includes("app.post('/api/tenders/convert'"), 'API debe exponer POST /api/tenders/convert.');
  assert(file.includes("app.post('/api/tender-convert'"), 'API debe exponer alias Vercel-safe POST /api/tender-convert.');
  assert(file.includes('directora.licitaciones@seguridadnacional.co'), 'API debe autorizar a Katherine por email.');
  assert(file.includes('Solo dirección o licitaciones puede ver este radar.'), 'API debe responder 403 para perfiles no autorizados.');
  assert(file.includes('fetchSecopSource'), 'API debe consultar SECOP para poblar radar de licitaciones.');
  assert(file.includes('fetchTvecEvents'), 'API debe consultar TVEC como tercera fuente activa.');
  assert(file.includes('TVEC_RELEVANT_AGGREGATIONS'), 'API debe declarar instrumentos TVEC relevantes.');
  assert(file.includes('fetchEsuProcesses'), 'API debe consultar ESU Contratación como cuarta fuente activa.');
  assert(file.includes('ESU_CONTRATACION_URL'), 'API debe declarar URL base de ESU Contratación.');
  assert(file.includes('ESU_DATOS_GOV_ENTITY_TERMS'), 'API debe declarar búsqueda ESU por entidad en datos.gov.co.');
  assert(file.includes('fetchEsuDatosGovProcesses'), 'API debe consultar procesos ESU vía datos.gov.co como respaldo sin hCaptcha.');
  assert(file.includes('datos.gov.co /'), 'API debe marcar el origen de procesos ESU encontrados en datos.gov.co.');
  assert(file.includes("source: 'ESU Contratación'"), 'API debe normalizar procesos ESU con source ESU Contratación.');
  assert(file.includes('ESU Contratación no disponible temporalmente'), 'API debe diagnosticar falla temporal de ESU sin tumbar otras fuentes.');
  assert(file.includes('TVEC no disponible temporalmente'), 'API debe diagnosticar falla temporal de TVEC sin tumbar SECOP.');
  assert(file.includes('Promise.allSettled'), 'API debe tolerar errores por fuente sin romper todo el radar.');
  assert(file.includes('section: classifyTenderSection'), 'API debe clasificar licitaciones en hacer/revisar/descartar.');
  assert(file.includes('psi_public_tenders'), 'API debe usar tabla psi_public_tenders para historizar licitaciones.');
  assert(file.includes('psi_tender_radar_runs'), 'API debe registrar ejecuciones en psi_tender_radar_runs.');
  assert(file.includes('tenderTableAvailable'), 'API debe tener fallback si la migración aún no existe.');
  assert(file.includes('external_source: `secop_radar:${tender.source}:${stableTenderKey(tender)}`'), 'Conversión debe usar external_source estable para prevenir duplicados.');
  assert(file.includes('converted_opportunity_id'), 'Conversión debe marcar la licitación con opportunity_id.');
}

console.log('tenders static checks passed');
