export type BehaviorStatus = 'inactivo' | 'atrasado' | 'al_dia';
export type BehaviorRules = Readonly<{ inactiveDays: number; agendaOkPct: number; version: string }>;
export type BehaviorRow = {
  profileId: string;
  name: string;
  lastFollowUpAt: string | null;
  daysSinceFollowUp: number | null;
  followUpsWeek: number;
  followUps30d: number;
  decisionsWeek: number;
  pendingDecisions: number;
  activeOpportunities: number;
  agendaPct: number | null;
  lastSeenAt: string | null;
  daysSinceSeen: number | null;
  goalPct: number | null;
  status: BehaviorStatus;
  reason: string;
};
export type BehaviorReport = { rules: BehaviorRules; weekStart: string; month: string; generatedAt: string; rows: BehaviorRow[] };
type BehaviorOpportunity = {
  id: string;
  owner_id?: string | null;
  service_type_code?: string | null;
  stage_code?: string | null;
  next_action_at?: string | null;
  frozen_until?: string | null;
  delete_requested_at?: string | null;
  offer_value?: number | string | null;
  approved_at?: string | null;
  updated_at?: string | null;
};
type BehaviorGoal = { user_id?: string | null; period_month?: string | null; sales_budget?: number | string | null };
export const BEHAVIOR_RULES: BehaviorRules;
export const BEHAVIOR_FOLLOW_UP_TYPES: readonly string[];
export const BEHAVIOR_STATUS_ORDER: readonly BehaviorStatus[];
export function bogotaDaysSince(value: string | Date | null | undefined, now?: Date): number | null;
export function bogotaWeekStart(now?: Date): string;
export function bogotaMonth(now?: Date): string;
export function monthlyGoalCompliance(input?: { opportunities?: BehaviorOpportunity[]; goals?: BehaviorGoal[]; month?: string; ownerId?: string | null }): { approved: number; budget: number; pct: number | null };
export function buildCommercialBehavior(input?: {
  salespeople?: Array<{ id: string; full_name?: string | null; role?: string | null }>;
  opportunities?: BehaviorOpportunity[];
  interactions?: Array<{ opportunity_id: string; created_by: string | null; interaction_type: string; created_at: string }>;
  decisionLogs?: Array<{ opportunity_id: string; changed_by: string | null; created_at: string; field_name?: string }>;
  lastSeen?: Array<{ profile_id: string; last_seen_at: string | null }>;
  goals?: BehaviorGoal[];
  now?: Date;
  rules?: BehaviorRules;
}): BehaviorReport;
