export type PrioritySignal = { code?: string };
export type CommercialPriorityRow = {
  id?: string;
  company_name?: string | null;
  owner_id?: string | null;
  owner_name?: string | null;
  regional_nombre?: string | null;
  stage_code?: string | null;
  stage_name?: string | null;
  service_type_code?: string | null;
  service_type_name?: string | null;
  customer_segment?: string | null;
  level?: string | null;
  signals?: PrioritySignal[] | null;
  evidence?: { next_action_at?: string | null } | null;
};
export type CommercialPriorityFilters = {
  query?: string;
  category?: string;
  owner?: string;
  regional?: string;
  stage?: string;
  service?: string;
  customerSegment?: string;
  level?: string;
  reviewedIds?: Set<string> | string[];
};
export type DashboardPriorityLinkFilters = {
  owner?: string | null;
  regional?: string | null;
  stage?: string | null;
  service?: string | null;
  segment?: string | null;
};
export type PriorityContextLabels = {
  owner?: string;
  regional?: string;
  stage?: string;
  service?: string;
  segment?: string;
};
export function priorityHasSignal(row: CommercialPriorityRow, code: string): boolean;
export function prioritiesHashFromDashboard(status: string, filters?: DashboardPriorityLinkFilters): string;
export function priorityContextSummary(filters?: CommercialPriorityFilters & { invalid?: boolean }, labels?: PriorityContextLabels): string;
export function categoryFromAlertsHash(hash: string): string;
export function filtersFromAlertsHash(hash: string): { category: string; owner: string; regional: string; stage: string; service: string; customerSegment: string; invalid: boolean };
export function priorityHashFiltersAreValid(rows: CommercialPriorityRow[] | null | undefined, filters?: CommercialPriorityFilters & { invalid?: boolean }): boolean;
export function priorityCategory(row: CommercialPriorityRow, category?: string): boolean;
export function filterCommercialPriorities<T extends CommercialPriorityRow>(rows: T[] | null | undefined, filters?: CommercialPriorityFilters): T[];
export function summarizeCommercialPriorities(rows: CommercialPriorityRow[] | null | undefined): { total: number; risk: number; missing: number; overdue: number; closing: number; managed: number; highValueStalled: number; stalledSustentacion: number };
