import type { ReactNode } from 'react';

export type TenderModuleView = 'radar' | 'seguimiento' | 'oportunidades' | 'configuracion';
export type TenderRequest = <T>(path: string, options?: RequestInit) => Promise<T>;
export type TenderSection = 'hacer' | 'revisar' | 'prioridad_baja';
export type TenderInternalStatus = 'nueva' | 'en_revision' | 'convertida_oportunidad' | 'descartada';
export type TenderDeadlineFilter = 'todas' | '0_7' | '8_15' | '16_30' | 'vencida' | 'sin_fecha';
export type TenderValueFilter = 'todas' | 'sin_valor' | 'lt_50m' | '50m_500m' | '500m_plus' | '1000m_plus';
export type TenderScoreFilter = 'todas' | 'alto' | 'medio' | 'bajo';
export type TenderSortKey = 'deadline' | 'value' | 'score' | 'entity' | 'source';
export type TenderRegionKey = 'todas' | 'bog_cundinamarca' | 'med_antioquia' | 'eje_cafetero' | 'cali_valle' | 'costa_caribe' | 'santanderes' | 'sur_occidente' | 'otros';
export type TenderTrackingStatus = 'pendiente_revision' | 'analizando' | 'esperando_informacion' | 'listo_para_decision' | 'bloqueado';

export type PublicTender = {
  id: string; stable_key?: string; source: string; section: TenderSection; internal_status?: TenderInternalStatus;
  converted_opportunity_id?: string | null; tracking_updated_at?: string | null; reviewed_at?: string | null; reviewed_by?: string | null;
  tracking_owner_id?: string | null; tracking_status?: TenderTrackingStatus | null; tracking_next_action?: string | null;
  tracking_due_at?: string | null; tracking_blocker?: string | null; tracking_last_note?: string | null; tracking_started_at?: string | null;
  detected_at?: string | null; last_seen_at?: string | null; entity: string; dept?: string; city?: string;
  ref?: string; process_id?: string; title: string; desc?: string; value: number; status?: string;
  category?: string; published?: string | null; deadline?: string | null; window?: string; days?: number | null;
  score: number; reasons: string[]; risks: string[]; url?: string;
};
export type TenderTrackingUpdate = { id: string; tracking_owner_id: string; tracking_status: TenderTrackingStatus; tracking_next_action?: string | null; tracking_due_at?: string | null; tracking_blocker?: string | null; note?: string | null; expected_tracking_updated_at: string | null };
export type TenderTrackingEvent = { id: string; tender_id: string; event_type: string; note?: string | null; from_status?: string | null; to_status?: string | null; assigned_to?: string | null; next_action?: string | null; due_at?: string | null; blocker?: string | null; created_by?: string | null; created_at: string };
export type TenderSourceDiagnostic = { source: string; status: 'ok' | 'error' | string; count?: number; message?: string };
export type TenderRadarPayload = { generatedAt: string; source?: string; diagnostics?: TenderSourceDiagnostic[]; totals: { all: number; hacer: number; revisar: number; prioridadBaja: number; highValue: number; urgent: number; enRevision?: number; convertidas?: number; descartadas?: number }; tenders: PublicTender[] };
export type TenderRadarFilters = { query: string; source: string; region: TenderRegionKey; deadline: TenderDeadlineFilter; value: TenderValueFilter; score: TenderScoreFilter; section: TenderSection | 'todas'; internalStatus: TenderInternalStatus | 'todas' };
export type TenderDocumentImportStatus = 'analisis_generado' | 'documentos_cargados' | 'fallo_importacion' | 'pendiente_documentos' | 'no_aplica' | 'error';
export type TenderConversionResult = { id: string; duplicate: boolean; document_import_status: TenderDocumentImportStatus; document_import_error: string | null };
export type TenderDocumentRefreshResult = { new_count: number; updated_count: number; unchanged_count: number; failed_count: number; analysis_generated: boolean };
export type TenderSearchProfile = { id: string; name: string; description?: string | null; region_key: TenderRegionKey; source_filter: string; section_filter: TenderSection | 'todas'; internal_status_filter: TenderInternalStatus | 'todas'; deadline_filter: TenderDeadlineFilter; value_filter: TenderValueFilter; score_filter: TenderScoreFilter; query_text?: string | null; is_default?: boolean; created_at?: string; updated_at?: string };
export type TenderCompanyProfile = { legal_name?: string | null; nit?: string | null; rup_status?: string | null; rup_updated_at?: string | null; rup_unspsc_codes?: string | null; authorized_services?: string | null; supervigilancia_license?: string | null; financial_capacity?: string | null; organizational_capacity?: string | null; experience_summary?: string | null; certifications?: string | null; recurring_documents?: string | null; disqualifications_notes?: string | null; useful_company_info?: string | null; source_document_name?: string | null; rup_import_notes?: string | null; updated_at?: string | null; updated_by_name?: string | null };
export type TenderCompanyDocument = { id: string; document_type: string; display_name: string; issued_at?: string | null; expires_at?: string | null; version: number; current: boolean; state: 'vigente' | 'vence_pronto' | 'vencido' | 'sin_vencimiento'; mime_type?: string | null; size_bytes: number; created_at: string; uploaded_by_name?: string | null; url?: string | null };
export type TenderDossier = { tender_id?: string; opportunity_id: string; entity?: string; title?: string; source?: string; url?: string | null; document_count: number; missing_document_count: number; document_import_status: string; document_import_error?: string | null; go_no_go?: string | null; risk?: string | null; checklist_progress?: { total?: number; auto_generated?: number; human_required?: number } | null; preparation_status?: string | null; human_pending_count?: number; sharepoint_status?: string | null; sharepoint_url?: string | null; dossier_error?: string | null };
export type TenderOpportunityFilter = 'all' | 'pending_decision' | 'go_authorized' | 'in_preparation' | 'submitted' | 'closed';
export type TenderOfferStatus = 'pendiente_decision' | 'en_preparacion' | 'lista_para_presentar' | 'presentada' | 'adjudicada' | 'no_adjudicada' | 'cerrada_no_go';
export type TenderOpportunitySummary = TenderDossier & {
  recommendation: string;
  decision: 'go' | 'no_go' | null;
  decided_by_name: string | null;
  decided_at: string | null;
  tender_offer_status: TenderOfferStatus;
};
export type TenderCurrentProfile = { id: string; full_name: string; role: string; microsoft_email?: string | null; active?: boolean; permissions?: string[]; identity_type?: 'human' | 'agent' | null };
export type TenderDocumentAnalysis = {
  run_id: string;
  snapshot_id: string;
  producer: 'siio_rules_v1' | 'HERMES-INTERIM' | 'AGT-002';
  method: 'rules' | 'agent_ai';
  status: 'completed' | 'failed';
  current: boolean;
  critical_open_count: number;
  created_at?: string | null;
  completed_at?: string | null;
  interaction_id?: string | null;
  recommendation?: string;
  risk?: string;
  summary?: string;
  generated_at?: string;
  findings?: string[];
  commercial_fit?: { status?: string; positives?: string[]; concerns?: string[] };
  strengths?: TenderAnalysisFinding[];
  weaknesses?: TenderAnalysisFinding[];
  blockers?: TenderAnalysisFinding[];
  questions?: TenderAnalysisFinding[];
  unverified?: TenderAnalysisFinding[];
  company_profile_crosscheck?: { status?: string; matches?: string[]; gaps?: TenderAnalysisFinding[]; profile_source?: string };
  next_action?: string;
  [key: string]: unknown;
};
export type TenderDocumentRecord = {
  id: string;
  name: string;
  size: number;
  mime_type?: string | null;
  document_type: string;
  current: boolean;
  storage_path?: string;
  uploaded_at: string;
  uploaded_by?: string | null;
  signed_url?: string | null;
  extracted_text?: string | null;
};
export type TenderDocumentsPayload = Partial<TenderDocumentRefreshResult> & {
  import_error?: { kind?: string; source?: string | null; created_at?: string | null; failure_marker?: string | null } | null;
  documents: TenderDocumentRecord[];
  analysis: TenderDocumentAnalysis | null;
  analyses: TenderDocumentAnalysis[];
  analysis_engine?: { requested: 'AGT-002'; used: 'AGT-002' | 'siio_rules_v1'; fallback: boolean; reason?: 'not_configured' | 'preview_unavailable'; reused?: boolean; human_review_required: true };
};
export type TenderAnalysisFinding = string | {
  id?: string;
  text?: string;
  critical?: boolean;
  evidence_refs?: string[];
};
export type TenderGoNoGoDecision = {
  id: string;
  opportunity_id: string;
  tender_id: string;
  decision: 'go' | 'no_go';
  analysis_interaction_id: string | null;
  analysis_run_id: string | null;
  justification: string | null;
  decided_by: string;
  decided_at: string;
  supersedes_decision_id?: string | null;
  psi_sales_profiles?: { full_name?: string | null } | null;
};
export type TenderGoNoGoDecisionInput = { opportunity_id: string; decision: 'go' | 'no_go'; analysis_run_id?: string | null; justification?: string | null };
export type TenderOfferPreparation = { status: string; interaction_id?: string; [key: string]: unknown };
export type TenderOfferStatusTransition = {
  id: string;
  opportunity_id: string;
  tender_id: string;
  actor_id: string;
  from_status: Exclude<TenderOfferStatus, 'pendiente_decision' | 'cerrada_no_go' | 'adjudicada' | 'no_adjudicada'>;
  to_status: Exclude<TenderOfferStatus, 'pendiente_decision' | 'cerrada_no_go' | 'en_preparacion'>;
  note: string | null;
  changed_at: string;
  psi_sales_profiles?: { full_name?: string | null } | null;
};
export type TenderOfferStatusPayload = { status: TenderOfferStatus; history: TenderOfferStatusTransition[] };
export type TenderOfferStatusTransitionInput = { opportunity_id: string; to_status: TenderOfferStatus; expected_current_status: TenderOfferStatus; note?: string | null };
export type TenderGoNoGoPayload = { decision: TenderGoNoGoDecision | null; history: TenderGoNoGoDecision[]; preparation: TenderOfferPreparation | null; analysis?: TenderDocumentAnalysis | null };
export type TenderGoNoGoPostPayload = {
  decision: {
    decision_id: string;
    supersedes_decision_id: string | null;
    decision: 'go' | 'no_go';
    preparation_id: string | null;
    preparation_created: boolean;
    tender_offer_status: TenderOfferStatus;
  };
  preparation: TenderOfferPreparation | null;
};
export type TenderModuleData = { currentProfile: TenderCurrentProfile; profiles: Array<{ id: string; full_name: string; role: string }> };
export type TendersModuleProps = { view: TenderModuleView; data: TenderModuleData; refresh: () => Promise<void>; request: TenderRequest; navigate: (hash: string) => void; children?: ReactNode };
