-- 014_siio_f2_foundation.sql
-- SIIO / F2 / F4 / Junta MVP foundation schema.
-- Proposal generated by Hermes. Review before applying to Supabase.

create table if not exists public.siio_fronts (
  id text primary key,
  name text not null,
  description text not null default '',
  owner_role text,
  status text not null default 'diseño' check (status in ('activo','diseño','pendiente','futuro')),
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_sources (
  id text primary key,
  name text not null,
  source_type text not null,
  related_fronts text[] not null default '{}',
  related_records text[] not null default '{}',
  url text,
  owner text,
  responsible_area text,
  trust_level text not null default 'pendiente' check (trust_level in ('oficial','oficial_requiere_validacion','referencia','restringida','pendiente')),
  status text not null default 'activa' check (status in ('activa','pendiente','historica','obsoleta')),
  permissions text not null default '',
  allowed_agent_use text not null default '',
  restrictions text not null default '',
  update_frequency text not null default 'bajo demanda',
  last_reviewed_at date,
  next_review_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_gerencial_records (
  id text primary key,
  front_id text not null references public.siio_fronts(id),
  title text not null,
  record_type text not null,
  objective text not null default '',
  area text,
  owner text,
  sponsor text,
  status text not null default 'diseño',
  priority text not null default 'media' check (priority in ('crítica','alta','media','baja')),
  semaforo text not null default 'amarillo' check (semaforo in ('verde','amarillo','rojo')),
  next_milestone text,
  next_action text,
  commitment_date date,
  blockers text,
  risks text,
  decision_required text,
  decision_owner text,
  source_ids text[] not null default '{}',
  executive_notes text,
  created_by uuid references public.psi_sales_profiles(id) on delete set null,
  updated_by uuid references public.psi_sales_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_decisions_commitments (
  id uuid primary key default gen_random_uuid(),
  item_type text not null check (item_type in ('decision','compromiso','bloqueo','riesgo')),
  origin text not null default 'gerencia',
  related_record_id text references public.siio_gerencial_records(id) on delete set null,
  description text not null,
  owner text,
  due_date date,
  status text not null default 'pendiente' check (status in ('pendiente','en_proceso','bloqueado','cerrado','vencido')),
  impact text check (impact in ('alto','medio','bajo') or impact is null),
  source_ids text[] not null default '{}',
  created_by uuid references public.psi_sales_profiles(id) on delete set null,
  updated_by uuid references public.psi_sales_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_monthly_board_reports (
  id text primary key,
  period_month date not null,
  status text not null default 'borrador' check (status in ('borrador','en_revision','aprobado','presentado')),
  generated_at timestamptz not null default now(),
  validated_by text,
  summary text not null default '',
  source_ids text[] not null default '{}',
  deck_url text,
  created_by uuid references public.psi_sales_profiles(id) on delete set null,
  updated_by uuid references public.psi_sales_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_board_sections (
  id uuid primary key default gen_random_uuid(),
  report_id text references public.siio_monthly_board_reports(id) on delete cascade,
  section_order integer not null,
  name text not null,
  content_required text not null default '',
  automation_level text not null default 'parcial' check (automation_level in ('automatico','parcial','manual')),
  human_review_required boolean not null default true,
  primary_source_ids text[] not null default '{}',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_financial_metrics (
  id uuid primary key default gen_random_uuid(),
  period_month date not null,
  category text not null,
  concept text not null,
  value_current numeric,
  value_comparison numeric,
  variation_abs numeric,
  variation_pct numeric,
  source_id text references public.siio_sources(id) on delete set null,
  validated_by text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_commercial_signals (
  id uuid primary key default gen_random_uuid(),
  period_month date not null,
  signal_type text not null,
  client_name text,
  monthly_value numeric,
  projected_value numeric,
  crm_record_url text,
  owner text,
  next_action text,
  source_id text references public.siio_sources(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_payroll_aggregates (
  id uuid primary key default gen_random_uuid(),
  period_month date not null,
  area text,
  total_people integer not null default 0,
  total_accrued numeric,
  total_deductions numeric,
  variation_abs numeric,
  alert text,
  source_id text references public.siio_sources(id) on delete set null,
  visibility_level text not null default 'restringido' check (visibility_level in ('gerencia','junta_agregado','restringido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.siio_strategic_opportunities (
  id text primary key,
  front_id text references public.siio_fronts(id) on delete set null,
  opportunity text not null,
  current_problem text,
  ai_solution text,
  benefited_area text,
  expected_impact text,
  ease text,
  priority text,
  status text,
  first_deliverable text,
  notes text,
  control_fields_missing text[] not null default '{}',
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_siio_records_front on public.siio_gerencial_records(front_id);
create index if not exists idx_siio_records_status on public.siio_gerencial_records(status);
create index if not exists idx_siio_records_semaforo on public.siio_gerencial_records(semaforo);
create index if not exists idx_siio_decisions_status on public.siio_decisions_commitments(status);
create index if not exists idx_siio_board_period on public.siio_monthly_board_reports(period_month);
create index if not exists idx_siio_financial_period on public.siio_financial_metrics(period_month);

alter table public.siio_fronts enable row level security;
alter table public.siio_sources enable row level security;
alter table public.siio_gerencial_records enable row level security;
alter table public.siio_decisions_commitments enable row level security;
alter table public.siio_monthly_board_reports enable row level security;
alter table public.siio_board_sections enable row level security;
alter table public.siio_financial_metrics enable row level security;
alter table public.siio_commercial_signals enable row level security;
alter table public.siio_payroll_aggregates enable row level security;
alter table public.siio_strategic_opportunities enable row level security;

-- Policy template: management roles only. Apply in implementation loop after confirming exact policy desired.
