begin;

-- Canonical, metadata-only company evidence registry (AGT-002 hotfix,
-- productive case 54190e51-15fb-46af-b0aa-8f13461a3110): psi_company_procurement_documents
-- was empty and psi_company_procurement_profile.supervigilancia_license carried a stale
-- free-text annotation, so AGT-002 asked a false question about a license that in fact
-- exists in the reviewed corporate corpus (Base Maestra provisional v0.2). This table
-- stores that corpus's per-entry metadata only — never a stored file, secret or signed
-- URL — with three explicitly separate status dimensions so a caller can never collapse
-- "the evidence exists" into "it is contractually applicable to a given case":
--   existence_status      — was this evidence reported as present in the reviewed corpus.
--   human_review_status   — has a human approved/rejected the entry (decision_humana*).
--   applicability_status  — does the entry apply to a specific tender/case (never implied
--                            by mere existence; starts and stays pending_case_validation
--                            until a case-specific human review sets it).
-- Versionable via (entry_id, version) with a single current=true row per entry_id, mirroring
-- psi_company_procurement_documents (026); no RPC is added here — this hotfix only ingests
-- the 17 currently active entries, it does not build a write path for future revisions.
create table if not exists public.psi_agt002_company_evidence_registry (
  id uuid primary key default gen_random_uuid(),
  entry_id text not null check (entry_id ~ '^[a-z][a-z0-9_]*$'),
  version integer not null check (version > 0),
  current boolean not null default true,
  document_class text not null check (nullif(btrim(document_class), '') is not null),
  classification text not null check (nullif(btrim(classification), '') is not null),
  estado_integracion text not null check (nullif(btrim(estado_integracion), '') is not null),
  sensibilidad text not null check (nullif(btrim(sensibilidad), '') is not null),
  source_reference text not null check (nullif(btrim(source_reference), '') is not null),
  item_id text check (item_id is null or nullif(btrim(item_id), '') is not null),
  duplicate_count integer check (duplicate_count is null or duplicate_count >= 0),
  hash text check (hash is null or hash ~ '^[0-9a-f]{64}$'),
  hash_contrastado_corpus_index boolean,
  zona_almacenamiento text not null check (nullif(btrim(zona_almacenamiento), '') is not null),
  utilidad_decisional text not null check (nullif(btrim(utilidad_decisional), '') is not null),
  accion_humana text not null check (nullif(btrim(accion_humana), '') is not null),
  human_gate text not null check (nullif(btrim(human_gate), '') is not null),
  control_de_uso text not null check (nullif(btrim(control_de_uso), '') is not null),
  -- Governance flags inherited from the manifest overlay (not per-entry in the
  -- source, but load-bearing for every entry): internal decision support only,
  -- no external submission authority, no automatic final approval.
  allowed_use jsonb not null default jsonb_build_object(
    'internal_decision_support', true,
    'external_submission_authority', false,
    'automatic_final_approval', false
  ) check (
    jsonb_typeof(allowed_use) = 'object'
    and allowed_use ? 'internal_decision_support'
    and allowed_use ? 'external_submission_authority'
    and allowed_use ? 'automatic_final_approval'
  ),
  metadata_only boolean not null,
  vigente_para_habilitacion boolean not null,
  existence_status text not null default 'reported' check (existence_status in ('verified', 'reported', 'not_verified')),
  human_review_status text not null default 'pending_human_review' check (human_review_status in ('pending_human_review', 'approved', 'rejected')),
  applicability_status text not null default 'pending_case_validation' check (applicability_status in ('pending_case_validation', 'applicable', 'not_applicable')),
  vigencia_text text not null check (nullif(btrim(vigencia_text), '') is not null),
  expiry date,
  decision_humana text check (decision_humana is null or nullif(btrim(decision_humana), '') is not null),
  decision_humana_fecha date,
  estado_posterior_decision text check (estado_posterior_decision is null or nullif(btrim(estado_posterior_decision), '') is not null),
  rollback_can_deactivate boolean not null default true,
  rollback_scope text not null default 'entry_id' check (rollback_scope = 'entry_id'),
  integration_active boolean not null default true,
  notes text,
  source_manifest_version text not null default 'v0.2-provisional-20260801' check (nullif(btrim(source_manifest_version), '') is not null),
  created_by uuid references public.psi_sales_profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entry_id, version),
  -- Existence can only ever be upgraded to 'verified' alongside a recorded human decision;
  -- mere presence in the ingested corpus can never auto-promote to verified/cumplido.
  check (existence_status <> 'verified' or (decision_humana is not null and decision_humana_fecha is not null)),
  check (human_review_status = 'pending_human_review' or (decision_humana is not null and decision_humana_fecha is not null)),
  check (applicability_status = 'pending_case_validation' or (
    human_review_status <> 'pending_human_review'
    and decision_humana is not null
    and decision_humana_fecha is not null
  ))
);

create unique index if not exists psi_agt002_company_evidence_registry_one_current_idx
  on public.psi_agt002_company_evidence_registry (entry_id)
  where current;

create index if not exists psi_agt002_company_evidence_registry_current_idx
  on public.psi_agt002_company_evidence_registry (entry_id, current, version desc);

drop trigger if exists trg_psi_agt002_company_evidence_registry_updated_at on public.psi_agt002_company_evidence_registry;
create trigger trg_psi_agt002_company_evidence_registry_updated_at before update on public.psi_agt002_company_evidence_registry
for each row execute function public.psi_sales_set_updated_at();

alter table public.psi_agt002_company_evidence_registry enable row level security;
revoke all on table public.psi_agt002_company_evidence_registry from public;
revoke all on table public.psi_agt002_company_evidence_registry from anon;
revoke all on table public.psi_agt002_company_evidence_registry from authenticated;
revoke all on table public.psi_agt002_company_evidence_registry from service_role;
grant select on table public.psi_agt002_company_evidence_registry to service_role;

-- Ingests the 17 currently active entries from the reviewed Base Maestra provisional
-- v0.2 (agt002_decision_knowledge_base_provisional_v0.2.json). Every row preserves the
-- source's own estado_integracion (INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA) and
-- is inserted with existence_status='reported' (never verified) and
-- applicability_status='pending_case_validation' (never applicable) — no entry is marked
-- as compliant/cumplido by this migration. expiry is populated only where the source's
-- "vigencia" text names an unambiguous end date (supervigilancia_operating_license,
-- rce_policy); every other entry's nuance stays in vigencia_text rather than being
-- guessed into a date. ON CONFLICT DO NOTHING keeps a re-run idempotent.
insert into public.psi_agt002_company_evidence_registry (
  entry_id, version, current, document_class, classification, estado_integracion, sensibilidad,
  source_reference, item_id, duplicate_count, hash, hash_contrastado_corpus_index, zona_almacenamiento,
  utilidad_decisional, accion_humana, human_gate, control_de_uso, metadata_only, vigente_para_habilitacion,
  existence_status, human_review_status, applicability_status, vigencia_text, expiry,
  decision_humana, decision_humana_fecha, estado_posterior_decision,
  rollback_can_deactivate, rollback_scope, integration_active, notes
) values
  ('supervigilancia_operating_license', 1, true, 'Licencia de funcionamiento SuperVigilancia', 'base_corporativa_reutilizable', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'LICENCIA DE FUNCIONAMIENTO SEGURIDAD NACIONAL (3 copias idénticas)', '01PXSUBJ3FM4EW7U2H35BZF3IFBM2PTWRA', 3, '45d9857f2a128853d53b6e7040dcff9551668b5e4e936dcc4e2c7249dce88255', true, 'base_maestra_restringida', 'Habilitante empresarial; revalidar vigencia y alcance antes de cada oferta', 'Gate: juridico_y_comercial. Acción recomendada: Aprobar metadatos y enlace canónico; conservar original restringido.', 'juridico_y_comercial', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. El estado ''vigente'' observado no constituye aprobación final; revalidar antes de cada oferta.', false, true, 'reported', 'pending_human_review', 'pending_case_validation', 'Resolución 20214100005697; vigencia observada hasta 2029-05-10', '2029-05-10', null, null, null, true, 'entry_id', true, 'Autoriza modalidades y medios observados en el acto. No sustituye consulta oficial vigente.'),
  ('rup', 1, true, 'Registro Único de Proponentes (RUP)', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'RUP 17.06.2026 (5 copias idénticas)', '01PXSUBJ7W2ZNHW6LASVAYXM6LNCLGRN2Z', 5, '8b7d472a37d80cf708cd5f5b4f9591bc0b651421a8b118725487e4e42e8ef856', true, 'base_maestra_restringida', 'Perfil, experiencia, clasificación y capacidad; no presentar sin versión reciente', 'Gate: juridico_y_financiero. Acción recomendada: Mantener como histórico canónico y solicitar RUP actualizado por proceso.', 'juridico_y_financiero', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Expedido 2026-06-17; el uso contractual exige certificado reciente según pliego', null, null, null, null, true, 'entry_id', true, 'Fuente ya usada en Base Maestra v0.1; conservar trazabilidad de la versión.'),
  ('rut', 1, true, 'Registro Único Tributario (RUT)', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'RUT SEGURIDAD NACIONAL 2026 (2 copias idénticas)', '01PXSUBJ5ECBLRKITF7JAZCRPLPYS3ZVIL', 2, '881f6ca54b3ee86533626c7605880b7273c71d542057a923dd4eebdb7c8275f6', true, 'base_maestra_restringida', 'Identificación tributaria; revalidar antes de presentar', 'Gate: juridico_y_financiero. Acción recomendada: Registrar identidad canónica y regla de actualización.', 'juridico_y_financiero', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Edición 2026; validar fecha de generación y cambios registrales', null, null, null, null, true, 'entry_id', true, 'No copiar datos de contacto o terceros a la capa general.'),
  ('communications_license', 1, true, 'Licencia o permisos de comunicaciones', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'alta_restringida', 'LICENCIA DE COMUNICACIONES (2 copias idénticas)', '01PXSUBJ4FOHHZ3H6XC5GLVVBZYQ2TA47W', 2, '93d2f7a7dae87786a965621b9fc2e2f91c0ca911e7bc47ce53cd05e46730040a', true, 'boveda_restringida', 'Sólo tras identificar acto, alcance y vigencia efectiva', 'Gate: juridico. Acción recomendada: Revisar original y localizar permiso vigente de MinTIC/autoridad competente.', 'juridico', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Acceso restringido; sólo metadatos y estado en capa general; conservar el soporte completo fuera de la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'No determinable del corpus sanitizado; documento de 63 páginas', null, null, null, null, true, 'entry_id', true, 'El clasificador la marcó erróneamente como personal; corregir taxonomía al aprobar.'),
  ('uniforms_resolution', 1, true, 'Resolución de uniformes y distintivos', 'base_corporativa_reutilizable', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'RES UNIFORMES SEGURIDAD NACIONAL', '01PXSUBJ2IWEVYKZ5NCJG2TS64BGQLHT2B', 1, 'cf8b74af151368015754d4e72d6b8a9ccec79e693023520e924d8d19966f623a', true, 'base_maestra_restringida', 'Soporte de autorización de diseños, colores y distintivos', 'Gate: juridico_y_operaciones. Acción recomendada: Aprobar metadatos y verificar vigencia regulatoria.', 'juridico_y_operaciones', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Resolución 20224100048477; validar que no exista acto posterior', null, null, null, null, true, 'entry_id', true, 'El acto corrige una resolución anterior; no usar para probar licencia de funcionamiento.'),
  ('no_fines_sanctions_certificate', 1, true, 'Certificado de multas y sanciones', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'Certificado sin multas y sanciones (2 copias idénticas)', '01PXSUBJ3VMDBVXXXKFFG23FMBPGD25OEX', 2, 'dbe65f7def3bcae11932ffbaad7c7ae9b2893bc16539aa5abffd6613563b83cf', true, 'base_maestra_restringida', 'Habilitante de control; validar ventana exacta para la fecha de cierre', 'Gate: juridico. Acción recomendada: Registrar fecha de expedición y alerta de vencimiento.', 'juridico', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Expedido 2026-06-18; vigencia declarada de 90 días hábiles', null, null, null, null, true, 'entry_id', true, 'La ausencia observada de sanciones no debe convertirse en conclusión permanente.'),
  ('authorized_weapons_list', 1, true, 'Listado de armas autorizadas', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'operativa_critica', 'LISTADO DE ARMAS - SEGURIDAD NACIONAL (2 copias idénticas)', '01PXSUBJ3DHD5YZQYH2BEZVVRHTHE7FS2F', 2, 'f05a33e21c5676fa4f9a6204f67c77a506e2f0ccb6321e8ebd0a093950edd441', true, 'boveda_restringida', 'Sólo validación de habilitación; nunca exponer seriales o inventario detallado', 'Gate: juridico_y_operaciones. Acción recomendada: Registrar sólo metadatos; obtener listado vigente por proceso.', 'juridico_y_operaciones', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Acceso restringido; sólo metadatos y estado en capa general; conservar el soporte completo fuera de la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Expedido 2026-06-19; vigencia declarada de 60 días', null, null, null, null, true, 'entry_id', true, 'No publicar inventario, seriales ni cantidades en la capa general.'),
  ('rce_policy', 1, true, 'Póliza de responsabilidad civil extracontractual', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'POLIZA RCE.zip (3 piezas)', '01PXSUBJ7DZDXFXP5SHJEKPRPP5VAQZXF4', 1, '7fd601428b7b5ad36e52fbbea8f2307b0d2d8d17d2d280c5293d4e5cf59cc3ed', true, 'base_maestra_restringida', 'Validar cobertura, límites, pago y requisitos del pliego', 'Gate: juridico_y_financiero. Acción recomendada: Registrar metadatos, vigencia y alerta; conservar carátula y pago restringidos.', 'juridico_y_financiero', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. El estado ''vigente'' observado no constituye aprobación final; revalidar antes de cada oferta.', false, true, 'reported', 'pending_human_review', 'pending_case_validation', 'Póliza observada: 2026-02-06 a 2027-02-06', '2027-02-06', null, null, null, true, 'entry_id', true, 'La suficiencia depende del proceso; la póliza no equivale a garantía de seriedad.'),
  ('collective_life_policy', 1, true, 'Póliza de seguro de vida colectivo', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'alta_restringida', 'Renovación 2026-2027 de seguro colectivo de vida', '01PXSUBJ57JDYC6AYCXZAIXOZ7NQOWLHTZ', 1, 'e20fc9357268700e4237f4dfdbe1db793ea75d9ad829940140bb434b6e0a93f8', true, 'boveda_restringida', 'Habilitante laboral obligatorio; demostrar vigencia a fecha de cierre', 'Gate: juridico_y_talento_humano. Acción recomendada: Registrar sólo metadatos y alerta; verificar cobertura 24 horas y aseguradora.', 'juridico_y_talento_humano', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Acceso restringido; sólo metadatos y estado en capa general; conservar el soporte completo fuera de la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Renovación 2026-2027; fechas y pago deben verificarse en original', null, null, null, null, true, 'entry_id', true, 'El clasificador la marcó como personal por contener asegurados; no exponer anexos nominales.'),
  ('accredited_experience', 1, true, 'Experiencia acreditada', 'biblioteca_de_experiencia_reutilizable', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'referencia_empresarial', 'EXPERIENCIA ACREDITADA', '01PXSUBJ33SSWS2QC6AVB3D6K57IUFZVWW', 1, '9f6a27af2ec26791d61215edec5d18020f883944cab004c226b5ba213bf656a6', true, 'base_maestra_restringida', 'Búsqueda y preselección de experiencia; no declarar cumplimiento automáticamente', 'Gate: juridico_y_tecnico. Acción recomendada: Desagregar contratos y certificaciones con hash, alcance y resultado.', 'juridico_y_tecnico', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Sin caducidad general; correspondencia contractual debe verificarse por requisito', null, null, null, null, true, 'entry_id', true, 'La revisión previa detectó contradicciones; requiere normalización antes de automatizar.'),
  ('financial_and_tax_pack', 1, true, 'Estados financieros, declaración de renta y soportes contables', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'financiera_alta', 'DOCUMENTOS FINANCIEROS (3 ZIP idénticos) + declaración de renta 2025', '01PXSUBJZSJHY53EUYYZBZ3WCVHOGNHFDC', 3, null, null, 'boveda_restringida', 'Evaluación de capacidad; sólo datos mínimos derivados en capa general', 'Gate: financiero_y_juridico. Acción recomendada: Separar estados, renta, certificaciones y anexos; no promover el ZIP completo.', 'financiero_y_juridico', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Acceso restringido; sólo metadatos y estado en capa general; conservar el soporte completo fuera de la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Corte 2025; actualización anual y según pliego', null, null, null, null, true, 'entry_id', true, 'Contiene soportes personales de profesionales contables y un anexo específico del proceso.'),
  ('bank_certificate', 1, true, 'Certificación bancaria corporativa', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'financiera_critica', 'Dentro de DOCUMENTOS FINANCIEROS; expedida 2026-06-22', '01PXSUBJZSJHY53EUYYZBZ3WCVHOGNHFDC', 3, '5ec470f047867b0cbeabe2e18ca02f950057b76e2f2cacf1d6516040181c9f76', true, 'boveda_restringida', 'Sólo cuando el proceso exija certificación bancaria vigente', 'Gate: financiero. Acción recomendada: Registrar sólo existencia, fecha y banco; ocultar número de cuenta.', 'financiero', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Acceso restringido; sólo metadatos y estado en capa general; conservar el soporte completo fuera de la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Expedida 2026-06-22; vigencia práctica dependiente del pliego', null, null, null, null, true, 'entry_id', true, 'Nunca exponer datos bancarios en el catálogo general.'),
  ('overtime_authorization', 1, true, 'Certificado o autorización de horas extras', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'CERTIFICADO HORAS EXTRAS', '01PXSUBJ5WS6V7OGDOAJFIX6DYLRQ3WZBB', 1, '253da91361c53bcbcbdf7655c65f217c864d64ba116222583c14b3ef4c60ebfa', true, 'base_maestra_restringida', 'Sólo si aplica al requisito y el acto está vigente', 'Gate: juridico_y_talento_humano. Acción recomendada: Verificar autoridad, resolución y vigencia en original.', 'juridico_y_talento_humano', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Vigencia no confirmada en esta revisión', null, null, null, null, true, 'entry_id', true, 'No inferir habilitación laboral sólo por el nombre del archivo.'),
  ('corporate_background_checks', 1, true, 'Antecedentes y consultas de la persona jurídica', 'base_corporativa_reutilizable_con_actualizacion', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'corporativa_restringida', 'Antecedentes fiscales/disciplinarios y medidas correctivas de la empresa', null, 1, null, null, 'base_maestra_restringida', 'Evidencia de control sólo para la fecha consultada', 'Gate: juridico. Acción recomendada: Crear clase por autoridad y conservar cada consulta con fecha/hash.', 'juridico', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Conservar original restringido; publicar sólo metadatos y estado en capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', false, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Consultas fechadas 2026-06-01; actualizar por proceso', null, null, null, null, true, 'entry_id', true, 'No mezclar con antecedentes del representante legal.'),
  ('legal_representative_vault', 1, true, 'Documentos y antecedentes de representantes legales', 'soporte_condicional_restringido', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'personal_alta', 'Identificación, antecedentes, inhabilidades y documentos militares del representante', null, 1, null, null, 'boveda_personal', 'Recuperar únicamente cuando el pliego lo exija y con acceso autorizado', 'Gate: juridico_y_privacidad. Acción recomendada: Catalogar clases y vigencias sin copiar identificadores ni imágenes.', 'juridico_y_privacidad', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Sólo metadatos; prohibido registrar nombres, identificaciones, correos, teléfonos, direcciones o contenido personal en la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Actualización por proceso y por autoridad emisora', null, null, null, null, true, 'entry_id', true, 'Excluir nombres, cédulas, firmas, direcciones y antecedentes de la capa general.'),
  ('personnel_credentials_vault', 1, true, 'Credenciales, formación, experiencia y afiliaciones de personal', 'soporte_condicional_restringido', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'personal_alta', 'Expedientes de personal, OMT, SST, supervisión, vigilancia y soporte técnico', null, 1, null, null, 'boveda_personal', 'Matching de requisitos por rol; nunca búsqueda general por identidad', 'Gate: talento_humano_y_privacidad. Acción recomendada: Crear inventario por rol/capacidad con referencias opacas, no por nombres.', 'talento_humano_y_privacidad', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Sólo metadatos; prohibido registrar nombres, identificaciones, correos, teléfonos, direcciones o contenido personal en la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Depende de credencial, curso, afiliación, relación laboral y fecha de cierre', null, null, null, null, true, 'entry_id', true, '1.004 documentos personales permanecen segregados; la revisión no los promovió.'),
  ('differential_scoring_support', 1, true, 'Soportes de criterios diferenciales', 'soporte_condicional_restringido', 'INTEGRADO_PROVISIONAL_PENDIENTE_REVISION_HUMANA', 'personal_y_laboral_alta', 'Discapacidad, mujeres vinculadas, industria nacional y otros factores de puntaje', null, 1, null, null, 'boveda_personal', 'Sólo si el proceso ofrece el factor y existe evidencia vigente', 'Gate: juridico_y_talento_humano. Acción recomendada: Mantener como checklist; no convertir en atributo corporativo permanente.', 'juridico_y_talento_humano', 'Uso interno exclusivo para apoyo a decisión; sin autoridad de presentación externa; sin aprobación final automática. Sólo metadatos; prohibido registrar nombres, identificaciones, correos, teléfonos, direcciones o contenido personal en la capa general. Estado no vigente/no verificado: puede usarse para informar disponibilidad o brecha documental, nunca para acreditar habilitación vigente.', true, false, 'reported', 'pending_human_review', 'pending_case_validation', 'Fotografía temporal; validar plantilla legal, umbral, personal y fecha', null, null, null, null, true, 'entry_id', true, 'Evitar inferencias sobre discapacidad, género o vínculo laboral.')
on conflict (entry_id, version) do nothing;

commit;
